/**
 * Example Resources Validation Tests
 *
 * Validates that example resources generated by the system
 * have correct JSON structure and required fields.
 */

import { describe, it, expect, vi } from "vitest";

// Mock logger to prevent console output
vi.mock("../../../src/utils/logging.js", () => ({
  logger: {
    error: vi.fn(),
    info: vi.fn(),
    debug: vi.fn(),
    warn: vi.fn(),
  },
}));

describe("Example Resource Validation", () => {
  describe("resource structure expectations", () => {
    // Expected structure based on generateExampleResource in handlers.ts
    const expectedBaseStructure = {
      metadata: ["name", "namespace", "labels", "annotations", "description"],
      system_metadata: ["creation_timestamp"],
    };

    it("should define expected metadata fields", () => {
      expect(expectedBaseStructure.metadata).toContain("name");
      expect(expectedBaseStructure.metadata).toContain("namespace");
    });

    it("should define expected system_metadata fields", () => {
      expect(expectedBaseStructure.system_metadata).toContain("creation_timestamp");
    });
  });

  describe("http_loadbalancer example structure", () => {
    const httpLbExample = {
      metadata: {
        name: "example-lb",
        namespace: "test-ns",
        labels: {},
        annotations: {},
        description: "Example http_loadbalancer",
      },
      spec: {
        domains: ["app.example.com"],
        http: {
          dns_volterra_managed: true,
        },
        default_route_pools: [
          {
            pool: {
              tenant: "your-tenant",
              namespace: "test-ns",
              name: "example-origin-pool",
            },
            weight: 1,
          },
        ],
        advertise_on_public_default_vip: {},
      },
      system_metadata: {
        creation_timestamp: "2024-01-01T00:00:00Z",
        modification_timestamp: "2024-01-01T00:00:00Z",
      },
    };

    it("should have metadata with name and namespace", () => {
      expect(httpLbExample.metadata.name).toBeDefined();
      expect(httpLbExample.metadata.namespace).toBeDefined();
    });

    it("should have spec with domains array", () => {
      expect(Array.isArray(httpLbExample.spec.domains)).toBe(true);
      expect(httpLbExample.spec.domains.length).toBeGreaterThan(0);
    });

    it("should have spec with default_route_pools", () => {
      expect(Array.isArray(httpLbExample.spec.default_route_pools)).toBe(true);
    });

    it("should have valid pool reference structure", () => {
      const pool = httpLbExample.spec.default_route_pools[0].pool;
      expect(pool.tenant).toBeDefined();
      expect(pool.namespace).toBeDefined();
      expect(pool.name).toBeDefined();
    });

    it("should have system_metadata with timestamps", () => {
      expect(httpLbExample.system_metadata.creation_timestamp).toBeDefined();
    });

    it("should have valid ISO timestamp format", () => {
      const timestamp = httpLbExample.system_metadata.creation_timestamp;
      expect(() => new Date(timestamp)).not.toThrow();
      // Timestamp should be parseable as valid date
      const date = new Date(timestamp);
      expect(date.getTime()).not.toBeNaN();
      // Format should match ISO 8601 pattern (with or without milliseconds)
      expect(timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(.\d{3})?Z$/);
    });
  });

  describe("origin_pool example structure", () => {
    const originPoolExample = {
      metadata: {
        name: "example-pool",
        namespace: "test-ns",
        labels: {},
        annotations: {},
        description: "Example origin_pool",
      },
      spec: {
        origin_servers: [
          {
            public_ip: {
              ip: "10.0.0.1",
            },
          },
        ],
        port: 80,
        no_tls: {},
        endpoint_selection: "LOCAL_PREFERRED",
        loadbalancer_algorithm: "ROUND_ROBIN",
      },
      system_metadata: {
        creation_timestamp: "2024-01-01T00:00:00Z",
      },
    };

    it("should have origin_servers array", () => {
      expect(Array.isArray(originPoolExample.spec.origin_servers)).toBe(true);
      expect(originPoolExample.spec.origin_servers.length).toBeGreaterThan(0);
    });

    it("should have port as number", () => {
      expect(typeof originPoolExample.spec.port).toBe("number");
      expect(originPoolExample.spec.port).toBeGreaterThan(0);
    });

    it("should have valid IP address format in origin_servers", () => {
      const ip = originPoolExample.spec.origin_servers[0].public_ip.ip;
      expect(ip).toMatch(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/);
    });

    it("should have loadbalancer_algorithm defined", () => {
      expect(originPoolExample.spec.loadbalancer_algorithm).toBeDefined();
    });
  });

  describe("dns_zone example structure", () => {
    const dnsZoneExample = {
      metadata: {
        name: "example-zone",
        namespace: "test-ns",
        labels: {},
        annotations: {},
        description: "Example dns_zone",
      },
      spec: {
        primary: {
          soa_parameters: {
            refresh: 3600,
            retry: 600,
            expire: 604800,
            negative_ttl: 1800,
          },
          default_rr_set_group: [],
        },
      },
      system_metadata: {
        creation_timestamp: "2024-01-01T00:00:00Z",
      },
    };

    it("should have primary configuration", () => {
      expect(dnsZoneExample.spec.primary).toBeDefined();
    });

    it("should have soa_parameters with required fields", () => {
      const soa = dnsZoneExample.spec.primary.soa_parameters;
      expect(soa.refresh).toBeDefined();
      expect(soa.retry).toBeDefined();
      expect(soa.expire).toBeDefined();
      expect(soa.negative_ttl).toBeDefined();
    });

    it("should have numeric SOA values", () => {
      const soa = dnsZoneExample.spec.primary.soa_parameters;
      expect(typeof soa.refresh).toBe("number");
      expect(typeof soa.retry).toBe("number");
      expect(typeof soa.expire).toBe("number");
      expect(typeof soa.negative_ttl).toBe("number");
    });
  });

  describe("app_firewall example structure", () => {
    const appFirewallExample = {
      metadata: {
        name: "example-waf",
        namespace: "test-ns",
        labels: {},
        annotations: {},
        description: "Example app_firewall",
      },
      spec: {
        detection_settings: {
          signature_selection_setting: {
            default_attack_type_settings: {},
            high_medium_accuracy_signatures: {},
          },
          enable_suppression: {},
          enable_threat_campaigns: {},
        },
        bot_protection_setting: {
          malicious_bot_action: "BLOCK",
          suspicious_bot_action: "REPORT",
          good_bot_action: "REPORT",
        },
      },
      system_metadata: {
        creation_timestamp: "2024-01-01T00:00:00Z",
      },
    };

    it("should have detection_settings", () => {
      expect(appFirewallExample.spec.detection_settings).toBeDefined();
    });

    it("should have bot_protection_setting", () => {
      expect(appFirewallExample.spec.bot_protection_setting).toBeDefined();
    });

    it("should have valid bot action values", () => {
      const bot = appFirewallExample.spec.bot_protection_setting;
      const validActions = ["BLOCK", "REPORT", "ALLOW", "FLAG"];
      expect(validActions).toContain(bot.malicious_bot_action);
      expect(validActions).toContain(bot.suspicious_bot_action);
      expect(validActions).toContain(bot.good_bot_action);
    });
  });

  describe("JSON serialization", () => {
    it("should produce valid JSON for http_loadbalancer", () => {
      const example = {
        metadata: { name: "test", namespace: "ns" },
        spec: { domains: ["test.com"] },
      };
      expect(() => JSON.stringify(example)).not.toThrow();
    });

    it("should produce formatted JSON with indentation", () => {
      const example = { metadata: { name: "test" } };
      const formatted = JSON.stringify(example, null, 2);
      expect(formatted).toContain("\n");
      expect(formatted).toContain("  ");
    });
  });
});
