# yamllint configuration for f5xc-api-mcp

extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true

ignore:
  - node_modules/
  - dist/
  - specs/
  - coverage/
