/**
 * Auto-Generated Test Fixtures
 * DO NOT EDIT - This file is generated by scripts/generate-test-fixtures.ts
 *
 * These fixtures are dynamically generated from the current OpenAPI specs
 * to ensure tests always use real values and don't hardcode spec content.
 *
 * Generated at: 2025-12-29T16:58:50.220Z
 * Total tools: 1548
 * Total domains: 38
 */

/**
 * Registry statistics
 */
export const REGISTRY_STATS = {
  totalTools: 1548,
  totalDomains: 38,
  domainCounts: {
    admin_console_and_ui: 2,
    api: 52,
    authentication: 9,
    bigip: 25,
    billing_and_usage: 23,
    blindfold: 32,
    bot_and_threat_defense: 20,
    cdn: 22,
    ce_management: 32,
    certificates: 20,
    cloud_infrastructure: 33,
    container_services: 16,
    data_and_privacy_security: 13,
    data_intelligence: 15,
    ddos: 68,
    dns: 52,
    generative_ai: 11,
    managed_kubernetes: 25,
    marketplace: 36,
    network: 98,
    network_security: 69,
    nginx_one: 14,
    object_storage: 7,
    observability: 45,
    rate_limiting: 15,
    secops_and_incident_response: 5,
    service_mesh: 44,
    shape: 180,
    sites: 106,
    statistics: 70,
    support: 47,
    telemetry_and_insights: 23,
    tenant_and_identity: 180,
    threat_campaign: 1,
    users: 12,
    virtual: 89,
    vpm_and_node_management: 1,
    waf: 36,
  },
} as const;

/**
 * Available domains (dynamically generated)
 */
export const AVAILABLE_DOMAINS = [
  "admin_console_and_ui",
  "api",
  "authentication",
  "bigip",
  "billing_and_usage",
  "blindfold",
  "bot_and_threat_defense",
  "cdn",
  "ce_management",
  "certificates",
  "cloud_infrastructure",
  "container_services",
  "data_and_privacy_security",
  "data_intelligence",
  "ddos",
  "dns",
  "generative_ai",
  "managed_kubernetes",
  "marketplace",
  "network",
  "network_security",
  "nginx_one",
  "object_storage",
  "observability",
  "rate_limiting",
  "secops_and_incident_response",
  "service_mesh",
  "shape",
  "sites",
  "statistics",
  "support",
  "telemetry_and_insights",
  "tenant_and_identity",
  "threat_campaign",
  "users",
  "virtual",
  "vpm_and_node_management",
  "waf",
] as const;

/**
 * Sample domain for testing (first available domain)
 */
export const SAMPLE_DOMAIN = "admin_console_and_ui";

/**
 * Sample tools by domain
 */
export const SAMPLE_TOOLS_BY_DOMAIN = {
  admin_console_and_ui: {
    toolName: "f5xc-api-adminconsoleandui-static-component-get",
    domain: "admin_console_and_ui",
    resource: "static-component",
    method: "GET",
    path: "/api/web/namespaces/{namespace}/static_components/{name}",
    operation: "get",
  },
  api: {
    toolName: "f5xc-api-api-api-crawler-create",
    domain: "api",
    resource: "api-crawler",
    method: "POST",
    path: "/api/config/namespaces/{metadata.namespace}/api_crawlers",
    operation: "create",
  },
  authentication: {
    toolName: "f5xc-api-authentication-api-credential-create",
    domain: "authentication",
    resource: "api-credential",
    method: "POST",
    path: "/api/web/namespaces/system/bulk_revoke/api_credentials",
    operation: "create",
  },
  bigip: {
    toolName: "f5xc-api-bigip-apm-create",
    domain: "bigip",
    resource: "apm",
    method: "POST",
    path: "/api/config/namespaces/{metadata.namespace}/apms",
    operation: "create",
  },
  billing_and_usage: {
    toolName: "f5xc-api-billingandusage-current-list",
    domain: "billing_and_usage",
    resource: "current",
    method: "GET",
    path: "/api/web/namespaces/system/usage_plans/current",
    operation: "list",
  },
} as const;

/**
 * Sample tools by operation type
 */
export const SAMPLE_TOOLS_BY_OPERATION = {
  create: {
    toolName: "f5xc-api-api-api-crawler-create",
    domain: "api",
    resource: "api-crawler",
    operation: "create",
  },
  get: {
    toolName: "f5xc-api-adminconsoleandui-static-component-get",
    domain: "admin_console_and_ui",
    resource: "static-component",
    operation: "get",
  },
  list: {
    toolName: "f5xc-api-adminconsoleandui-static-component-list",
    domain: "admin_console_and_ui",
    resource: "static-component",
    operation: "list",
  },
  delete: {
    toolName: "f5xc-api-api-api-crawler-delete",
    domain: "api",
    resource: "api-crawler",
    operation: "delete",
  },
  update: {
    toolName: "f5xc-api-api-api-crawler-update",
    domain: "api",
    resource: "api-crawler",
    operation: "update",
  },
} as const;

/**
 * Sample resources
 */
export const SAMPLE_RESOURCES = [
  "static-component",
  "api-crawler",
  "api-credential",
  "apm",
  "current",
] as const;

/**
 * First available tool (for basic tests)
 */
export const FIRST_TOOL = {
  toolName: "f5xc-api-adminconsoleandui-static-component-get",
  domain: "admin_console_and_ui",
  resource: "static-component",
  method: "GET",
  path: "/api/web/namespaces/{namespace}/static_components/{name}",
  operation: "get",
} as const;

/**
 * Tools with rich metadata (for metadata-specific tests)
 */
export const RICH_METADATA_SAMPLES = {
  withDangerLevel: {
    toolName: "f5xc-api-adminconsoleandui-static-component-get",
    dangerLevel: "low",
  },
  withOperationMetadata: { toolName: "f5xc-api-adminconsoleandui-static-component-get" },
  withValidationRules: null,
  withParameters: {
    toolName: "f5xc-api-adminconsoleandui-static-component-get",
    pathParamCount: 2,
    queryParamCount: 1,
  },
} as const;

/**
 * Helper to get a valid tool name for testing
 * @returns First available tool name from registry
 */
export function getValidToolName(): string {
  return FIRST_TOOL.toolName;
}

/**
 * Helper to get a valid domain for testing
 * @returns First available domain from registry
 */
export function getValidDomain(): string {
  return SAMPLE_DOMAIN;
}

/**
 * Helper to get sample tool for a specific operation type
 */
export function getSampleToolByOperation(
  operation: "create" | "get" | "list" | "delete" | "update"
): {
  toolName: string;
  domain: string;
  resource: string;
  operation: string;
} | null {
  return (
    (
      SAMPLE_TOOLS_BY_OPERATION as Record<
        string,
        { toolName: string; domain: string; resource: string; operation: string } | undefined
      >
    )[operation] ?? null
  );
}
