/**
 * Tool Registry - All generated MCP tools
 * DO NOT EDIT - This file is auto-generated by scripts/generate.ts
 */

import type { ParsedOperation } from "../generator/openapi-parser.js";

import { appstackTools } from "./generated/appstack/index.js";
import { coreTools } from "./generated/core/index.js";
import { dnsTools } from "./generated/dns/index.js";
import { networkTools } from "./generated/network/index.js";
import { securityTools } from "./generated/security/index.js";
import { siteTools } from "./generated/site/index.js";
import { waapTools } from "./generated/waap/index.js";

/**
 * All registered tools from all domains
 */
export const allTools: ParsedOperation[] = [
  ...appstackTools,
  ...coreTools,
  ...dnsTools,
  ...networkTools,
  ...securityTools,
  ...siteTools,
  ...waapTools,
];

/**
 * Get tools by domain
 */
export function getToolsByDomain(domain: string): ParsedOperation[] {
  return allTools.filter((tool) => tool.domain === domain);
}

/**
 * Get tool by name
 */
export function getToolByName(name: string): ParsedOperation | undefined {
  return allTools.find((tool) => tool.toolName === name);
}

/**
 * Get all domain names
 */
export function getAllDomains(): string[] {
  return [...new Set(allTools.map((tool) => tool.domain))];
}

/**
 * Get tool count by domain
 */
export function getToolCountByDomain(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const tool of allTools) {
    counts[tool.domain] = (counts[tool.domain] ?? 0) + 1;
  }
  return counts;
}

export default allTools;
