/**
 * Tool Registry - All generated MCP tools
 * DO NOT EDIT - This file is auto-generated by scripts/generate.ts
 */

import type { ParsedOperation } from "../generator/openapi-parser.js";

import { ai_intelligenceTools } from "./generated/ai_intelligence/index.js";
import { api_securityTools } from "./generated/api_security/index.js";
import { applicationsTools } from "./generated/applications/index.js";
import { bigipTools } from "./generated/bigip/index.js";
import { billingTools } from "./generated/billing/index.js";
import { cdnTools } from "./generated/cdn/index.js";
import { configTools } from "./generated/config/index.js";
import { identityTools } from "./generated/identity/index.js";
import { infrastructureTools } from "./generated/infrastructure/index.js";
import { infrastructure_protectionTools } from "./generated/infrastructure_protection/index.js";
import { integrationsTools } from "./generated/integrations/index.js";
import { load_balancerTools } from "./generated/load_balancer/index.js";
import { networkingTools } from "./generated/networking/index.js";
import { nginxTools } from "./generated/nginx/index.js";
import { observabilityTools } from "./generated/observability/index.js";
import { operationsTools } from "./generated/operations/index.js";
import { securityTools } from "./generated/security/index.js";
import { service_meshTools } from "./generated/service_mesh/index.js";
import { shape_securityTools } from "./generated/shape_security/index.js";
import { subscriptionsTools } from "./generated/subscriptions/index.js";
import { tenant_managementTools } from "./generated/tenant_management/index.js";
import { vpnTools } from "./generated/vpn/index.js";

/**
 * All registered tools from all domains
 */
export const allTools: ParsedOperation[] = [
  ...ai_intelligenceTools,
  ...api_securityTools,
  ...applicationsTools,
  ...bigipTools,
  ...billingTools,
  ...cdnTools,
  ...configTools,
  ...identityTools,
  ...infrastructureTools,
  ...infrastructure_protectionTools,
  ...integrationsTools,
  ...load_balancerTools,
  ...networkingTools,
  ...nginxTools,
  ...observabilityTools,
  ...operationsTools,
  ...securityTools,
  ...service_meshTools,
  ...shape_securityTools,
  ...subscriptionsTools,
  ...tenant_managementTools,
  ...vpnTools,
];

/**
 * Get tools by domain
 */
export function getToolsByDomain(domain: string): ParsedOperation[] {
  return allTools.filter((tool) => tool.domain === domain);
}

/**
 * Get tool by name
 */
export function getToolByName(name: string): ParsedOperation | undefined {
  return allTools.find((tool) => tool.toolName === name);
}

/**
 * Get all domain names
 */
export function getAllDomains(): string[] {
  return [...new Set(allTools.map((tool) => tool.domain))];
}

/**
 * Get tool count by domain
 */
export function getToolCountByDomain(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const tool of allTools) {
    counts[tool.domain] = (counts[tool.domain] ?? 0) + 1;
  }
  return counts;
}

export default allTools;
